package pkg.nward.hw5;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;

import java.awt.BorderLayout;
import java.awt.FlowLayout;

import javax.swing.JButton;

import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JTextArea;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.JLabel;

public class Program {

	private JFrame frame;
	private JTextField txtFilename;
	private JTextArea boxEntry;
	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Program window = new Program();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public Program() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	
	//this was all auto-generated by the UI plugin i used
	private void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 528, 341);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		JPanel buttonPanel = new JPanel();
		frame.getContentPane().add(buttonPanel, BorderLayout.SOUTH);
		buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		
		JButton btnSave = new JButton("Save");
		btnSave.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
			TextFile f = new TextFile();
			f.setName(txtFilename.getText());
			try {
				f.WriteToFile(boxEntry.getText());
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			}
		});
		
		txtFilename = new JTextField();
		txtFilename.addFocusListener(new FocusAdapter() {
			@Override
			public void focusGained(FocusEvent e) {
			txtFilename.setText(" ");
			}
		});
		txtFilename.setText("filename");
		buttonPanel.add(txtFilename);
		txtFilename.setColumns(10);
		buttonPanel.add(btnSave);
		
		
		
		//This is where I'm having trouble, I need some guidance on reading the files and what
		//to do with the output...
		
		JButton btnOpen = new JButton("Open");
		btnOpen.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				TextFile f = new TextFile();
				f.setName(txtFilename.getText());
				try {
					boxEntry.setText(f.ReadFromFile());
				} catch (FileNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
	
		buttonPanel.add(btnOpen);
		
		JButton btnExit = new JButton("Exit");
		btnExit.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
			System.exit(0);
			}
		});
		buttonPanel.add(btnExit);
		
		boxEntry = new JTextArea();
		frame.getContentPane().add(boxEntry, BorderLayout.CENTER);
	}

}
